begin;
select plan(20);
select has_table('public', 'publishing_queue', 'publishing queue exists');
select has_table('public', 'publish_attempts', 'publish attempts exist');
select has_table('public', 'publish_status_events', 'publish status events exist');
select has_table('public', 'publish_consents', 'publish consents exist');
select ok((select relrowsecurity from pg_class where oid='public.publishing_queue'::regclass), 'queue RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.publish_attempts'::regclass), 'attempt RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.publish_status_events'::regclass), 'event RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.publish_consents'::regclass), 'consent RLS enabled');
select policies_are('public', 'publishing_queue', array['publishing_queue_owner_read'], 'queue has owner-only read policy');
select policies_are('public', 'publish_attempts', array['publish_attempts_owner_read'], 'attempts have owner-only read policy');
select policies_are('public', 'publish_status_events', array['publish_status_events_owner_read'], 'events have owner-only read policy');
select policies_are('public', 'publish_consents', array['publish_consents_owner_read'], 'consents have owner-only read policy');
select ok(not has_table_privilege('anon','public.publishing_queue','select'), 'anonymous cannot read queue');
select ok(not has_table_privilege('anon','public.publish_consents','select'), 'anonymous cannot read consents');
select ok(has_table_privilege('authenticated','public.publishing_queue','select'), 'authenticated owner can select through RLS');
select ok(not has_table_privilege('authenticated','public.publishing_queue','insert'), 'browser cannot bypass queue service');
select ok(not has_table_privilege('authenticated','public.publishing_queue','update'), 'browser cannot mutate queue state');
select ok(not has_table_privilege('authenticated','public.publish_attempts','insert'), 'browser cannot forge attempts');
select ok(not has_table_privilege('authenticated','public.publish_status_events','update'), 'status history is append-only to browser roles');
select ok(has_table_privilege('service_role','public.publishing_queue','update'), 'server publisher can advance queue');
select * from finish();
rollback;
