import Link from "next/link";
import {redirect} from "next/navigation";
import {PageHeading} from "@/components/page-heading";
import {getCommerceOverview} from "@/features/commerce/services";
import {createClient} from "@/lib/supabase/server";

export default async function CommercePage(){const client=await createClient(),{data}=await client.auth.getUser();if(!data.user)redirect("/login");const overview=await getCommerceOverview(client,data.user.id);return <><PageHeading eyebrow="TIKTOK SHOP FOUNDATION" title="Affiliate Commerce" description="แยก content fit ออกจาก commerce eligibility และไม่ attach สินค้าจริง" action={<Link className="secondary-action" href="/commerce/products">ดูสินค้า →</Link>}/>
  <section className="stats-grid compact-stats"><article className="stat-card blue"><p>Accounts</p><strong>{overview.accounts.length}</strong><small>ทุกโหมดยังสร้าง content ได้</small></article><article className="stat-card green"><p>Affiliate ready</p><strong>{overview.accounts.filter(a=>a.commerce_profile?.commerce_status==="AFFILIATE_READY").length}</strong><small>ผ่านสิทธิ์จริงครบ</small></article><article className="stat-card amber"><p>Eligible products</p><strong>{overview.eligibility.filter(e=>e.commerce_eligible).length}</strong><small>account-product pairs</small></article><article className="stat-card violet"><p>API mode</p><strong>MOCK</strong><small>real Shop API disabled</small></article></section>
  <section className="panel radar-section"><div className="panel-heading"><div><p className="eyebrow">CREATOR COMMERCE</p><h2>Account readiness</h2></div></div><div className="data-list">{overview.accounts.map(a=><div key={a.id}><strong>{a.display_name} · {a.effective_mode}</strong><span>{a.commerce_profile?.commerce_status??"NOT_SYNCED"}</span><small>{a.follower_count.toLocaleString("th-TH")} followers · Shop {a.connection?.authorization_status??"NOT_CONNECTED"} · cart {a.cart_enabled===true?"READY":"NO"} · region {a.commerce_profile?.region??"—"}</small><Link href={`/commerce/accounts/${a.id}`}>ดู Commerce account →</Link></div>)}</div></section>
  <section className="panel radar-section"><h2>ข้อจำกัดที่บังคับใช้</h2><p>Follower count ไม่เท่ากับ Affiliate readiness · TikTok Login ไม่เท่ากับ TikTok Shop authorization · Growth publishing ไม่ถูกบล็อกเมื่อ Shop unavailable · ไม่มี fake cart หรือ product attachment</p></section></>}
