import type { TikTokAccount } from "@/features/accounts/types";
import type { Product,ProductScore,ProductSnapshot,Trend } from "@/features/products/types";
import type { CategoryProductInput } from "./types";

export const CATEGORY_FIXTURE_TIME="2026-09-15T03:00:00.000Z";
type Scenario={count:number;momentum:number;velocity:number;acceleration:number;commission:number;opportunity:number;competition:number;creative:number;trend:Trend;units:number};
const scenarios:Record<string,Scenario>={
 A:{count:21,momentum:12,velocity:2,acceleration:-.1,commission:35,opportunity:18,competition:.65,creative:.35,trend:"STABLE",units:100},
 B:{count:12,momentum:76,velocity:55,acceleration:.8,commission:68,opportunity:75,competition:.35,creative:.85,trend:"ACCELERATING",units:500},
 C:{count:14,momentum:62,velocity:80,acceleration:-.7,commission:65,opportunity:58,competition:.92,creative:.2,trend:"FALLING",units:5000},
 D:{count:1,momentum:88,velocity:90,acceleration:1.2,commission:80,opportunity:85,competition:.1,creative:.9,trend:"ACCELERATING",units:20},
 E:{count:10,momentum:72,velocity:48,acceleration:.55,commission:3,opportunity:8,competition:.3,creative:.9,trend:"ACCELERATING",units:400},
 F:{count:10,momentum:55,velocity:25,acceleration:.15,commission:96,opportunity:88,competition:.3,creative:.7,trend:"RISING",units:300},
};
const categoryNames:Record<string,string>={A:"one-giant",B:"home",C:"saturated-fashion",D:"low-data",E:"beauty",F:"gadgets"};
const score=(id:string,index:number,s:Scenario):ProductScore=>{const giant=id==="A"&&index===0;return{calculated_at:CATEGORY_FIXTURE_TIME,score_version:"product-momentum-v1",sales_velocity:giant?1000:s.velocity,sales_acceleration:giant?2:s.acceleration,price_attractiveness:id==="E"?45:id==="F"?90:70,commission_score:giant?80:s.commission,rating_score:80,review_confidence:.9,competition_score:100-s.competition*100,creative_potential_score:s.creative*100,data_confidence:.9,product_momentum_score:giant?99:s.momentum,viral_opportunity_base_score:giant?95:s.opportunity,explanation_json:{signals:{},confidence:.9,historyHours:24,salesDelta:s.units,staleHours:0,counterReset:false,velocities:{"1h":s.velocity,"6h":s.velocity,"24h":s.velocity},acceleration:s.acceleration,trend:giant?"ACCELERATING":s.trend,assumptions:[]}};};
export function categoryFixtureInputs(id:string):CategoryProductInput[]{const s=scenarios[id];return Array.from({length:s.count},(_,index)=>{const productId=`category-${id}-${index}`;const product:Product={id:productId,owner_id:"fixture-owner",external_provider:"mock",external_product_id:productId,title:`Category ${id} product ${index+1}`,slug:productId,category_key:categoryNames[id],image_url:null,product_url:null,currency:"THB",current_price:500,original_price:650,commission_rate:id==="E"?.005:id==="F"?.3:.15,commission_amount:id==="E"?2:id==="F"?150:60,rating:4.7,review_count:500,units_sold:s.units,status:"available",provider_metadata:{fixture:id},first_seen_at:"2026-09-14T03:00:00.000Z",last_seen_at:CATEGORY_FIXTURE_TIME,created_at:CATEGORY_FIXTURE_TIME,updated_at:CATEGORY_FIXTURE_TIME};const history:ProductSnapshot[]=[0,24].map((hours,i)=>({...product,id:`${productId}-${i}`,product_id:productId,captured_at:new Date(Date.parse(CATEGORY_FIXTURE_TIME)-(24-hours)*3600000).toISOString(),ingestion_event_id:`${productId}-${i}`,price:product.current_price,competition:s.competition,creative_potential:s.creative,units_sold:i?s.units:Math.max(0,s.units-Math.round(s.velocity*24))}));return{product,score:score(id,index,s),history};});}
export function fixtureAccounts():TikTokAccount[]{return [["account-a","Growth Beauty","GROWTH"],["account-b","Affiliate Home","AFFILIATE"],["account-c","Affiliate Gadget","AFFILIATE"]].map(([id,name,mode])=>({id,owner_id:"fixture-owner",display_name:name,username:id,follower_count:5000,following_count:0,mode:mode as "GROWTH"|"AFFILIATE",effective_mode:mode as "GROWTH"|"AFFILIATE",shop_creator_eligible:true,ecommerce_permission:true,cart_enabled:true,daily_post_target:3,daily_post_hard_limit:15,account_status:"active",authorization_status:"authorized",preferred_categories:[],account_notes:null,last_synced_at:CATEGORY_FIXTURE_TIME,is_mock:true,created_at:CATEGORY_FIXTURE_TIME,updated_at:CATEGORY_FIXTURE_TIME}));}
