import {describe,expect,it,vi} from "vitest";
import {FalWanProviderError,FalWanVideoProvider,generateAcceptedFalWanMaster,type FalWanClient} from "./fal-wan";
import type {RenderedVideo,VideoQualityInput} from "./types";
import {falAutoModeAvailability} from "./provider-routing";

const key="fal-test-key-never-log-123456789",videoBytes=new Uint8Array([0,1,2,3]),videoUrl="https://example.invalid/video.mp4";
function client(statuses:Array<{status?:string;error?:unknown}>=[{status:"COMPLETED"}],result={data:{video:{url:videoUrl}},requestId:"req-1"}){const submit=vi.fn(async(_endpoint:string,_input:Record<string,unknown>)=>({request_id:"req-1"})),status=vi.fn(async(_endpoint:string,_requestId:string)=>statuses.shift()??{status:"COMPLETED"}),getResult=vi.fn(async(_endpoint:string,_requestId:string)=>result);return{value:{upload:vi.fn(async(_file:Blob)=>"https://example.invalid/input.jpg"),submit,status,result:getResult} satisfies FalWanClient,submit,status,getResult}}
const fetchVideo=vi.fn(async()=>new Response(videoBytes,{status:200,headers:{"content-type":"video/mp4"}})) as unknown as typeof fetch;
const input={image:new Blob([new Uint8Array([1])],{type:"image/jpeg"}),prompt:"Commercial portrait product video",resolution:"720p" as const,aspectRatio:"9:16" as const,maxCostUsd:.10};
const media:RenderedVideo={path:"memory.mp4",duration:8,width:720,height:1280,fps:30,videoCodec:"h264",audioCodec:null,hasAudio:false,sizeBytes:100_000};
const qualityInput=(value:RenderedVideo):VideoQualityInput=>({...value,overlay:[],scenes:[],productVisible:true,ctaVisible:true,malformedAssets:false,inheritedRisk:"SAFE"});

describe("FalWanVideoProvider",()=>{
  it("requires FAL_KEY and never exposes it in failures",()=>{const mock=client(),provider=new FalWanVideoProvider({client:mock.value});expect(provider.isAvailable()).toBe(false);expect(provider.getFailureReason(new Error(`request ${key} failed`)).message).not.toContain(key)});
  it("reports the official Turbo capabilities without inventing frame controls",()=>expect(new FalWanVideoProvider({client:client().value}).getCapabilities()).toMatchObject({imageToVideo:true,resolutions:["480p","580p","720p"],aspectRatios:["auto","16:9","9:16","1:1"],sourceDuration:"PROVIDER_DEFINED",configurableFrames:false,queue:true}));
  it("estimates current per-video prices",()=>{const provider=new FalWanVideoProvider({client:client().value});expect(provider.estimateCost({resolution:"720p"})).toBe(.1);expect(provider.estimateCost({resolution:"580p"})).toBe(.075);expect(provider.estimateCost({resolution:"480p"})).toBe(.05)});
  it("submits, polls and downloads one generation with no paid retry",async()=>{const mock=client(),provider=new FalWanVideoProvider({apiKey:key,client:mock.value,fetchImpl:fetchVideo,sleep:async()=>{},pollIntervalMs:0});const result=await provider.generate(input);expect(result).toMatchObject({requestId:"req-1",actualCostUsd:.1,retryCount:0,resolution:"720p",aspectRatio:"9:16",sourceDurationSeconds:null});expect(mock.submit).toHaveBeenCalledOnce();const payload=mock.submit.mock.calls[0]?.[1];expect(payload).toMatchObject({resolution:"720p",aspect_ratio:"9:16",enable_safety_checker:true,enable_output_safety_checker:true});expect(payload).not.toHaveProperty("num_frames");expect(payload).not.toHaveProperty("frames_per_second")});
  it("records the request identity before polling and can retrieve without a second paid submit",async()=>{const mock=client(),events:string[]=[],provider=new FalWanVideoProvider({apiKey:key,client:mock.value,fetchImpl:fetchVideo,sleep:async()=>{},pollIntervalMs:0});await provider.generate({...input,onSubmitted:async requestId=>{events.push(requestId);expect(mock.status).not.toHaveBeenCalled()}});expect(events).toEqual(["req-1"]);await provider.retrieve("req-1");expect(mock.submit).toHaveBeenCalledOnce();expect(mock.getResult).toHaveBeenCalledTimes(2)});
  it("blocks a paid request above the cap before submission",async()=>{const mock=client(),provider=new FalWanVideoProvider({apiKey:key,client:mock.value,fetchImpl:fetchVideo});await expect(provider.generate({...input,maxCostUsd:.09})).rejects.toMatchObject({code:"BUDGET_EXCEEDED"});expect(mock.submit).not.toHaveBeenCalled()});
  it("keeps Auto Mode closed until fal is keyed and production approved",()=>{expect(falAutoModeAvailability({keyPresent:true,state:"PRIMARY_CANDIDATE"})).toMatchObject({providerAvailable:false,state:"WAITING_FOR_PROVIDER",reason:"OWNER_APPROVAL_REQUIRED"});expect(falAutoModeAvailability({keyPresent:false,state:"PRODUCTION_APPROVED"})).toMatchObject({providerAvailable:false,state:"WAITING_FOR_PROVIDER",reason:"FAL_KEY_MISSING"});expect(falAutoModeAvailability({keyPresent:true,state:"PRODUCTION_APPROVED"})).toMatchObject({providerAvailable:true,state:"READY",reason:null})});
  it("maps provider and safety failures without retrying",async()=>{const failed=client([{status:"FAILED",error:"provider unavailable"}]),provider=new FalWanVideoProvider({apiKey:key,client:failed.value,sleep:async()=>{},pollIntervalMs:0});await expect(provider.generate(input)).rejects.toMatchObject({code:"PROVIDER_FAILED",retryable:false,actualCostUsd:.1});expect(failed.submit).toHaveBeenCalledOnce();const blocked=client([{status:"FAILED",error:"blocked by safety checker"}]);await expect(new FalWanVideoProvider({apiKey:key,client:blocked.value,sleep:async()=>{},pollIntervalMs:0}).generate(input)).rejects.toMatchObject({code:"SAFETY_REJECTED"})});
  it("times out without an automatic paid retry",async()=>{const mock=client([{status:"IN_PROGRESS"},{status:"IN_PROGRESS"}]),provider=new FalWanVideoProvider({apiKey:key,client:mock.value,sleep:async()=>{},pollIntervalMs:0,maxPollAttempts:2});await expect(provider.generate(input)).rejects.toMatchObject({code:"TIMEOUT",retryable:false});expect(mock.submit).toHaveBeenCalledOnce()});
  it("treats a lost submit response as possibly charged and never retries",async()=>{const mock=client();mock.submit.mockRejectedValueOnce(new Error("connection closed after submit"));const provider=new FalWanVideoProvider({apiKey:key,client:mock.value});await expect(provider.generate(input)).rejects.toMatchObject({requestId:null,actualCostUsd:.1,retryable:false});expect(mock.submit).toHaveBeenCalledOnce()});
  it("fails the master pipeline below quality 85",async()=>{const mock=client(),provider=new FalWanVideoProvider({apiKey:key,client:mock.value,fetchImpl:fetchVideo,sleep:async()=>{}});await expect(generateAcceptedFalWanMaster({provider,request:input,inspect:async()=>media,qualityInput,evaluate:()=>({score:84,status:"RETRY",explanation:{}}),store:async()=>"never"})).rejects.toBeInstanceOf(FalWanProviderError)});
  it("stores only a quality-passing master",async()=>{const mock=client(),provider=new FalWanVideoProvider({apiKey:key,client:mock.value,fetchImpl:fetchVideo,sleep:async()=>{}}),store=vi.fn(async()=>"owner/master/provider-original.mp4");const result=await generateAcceptedFalWanMaster({provider,request:input,inspect:async()=>media,qualityInput,evaluate:()=>({score:95,status:"PASS",explanation:{}}),store});expect(result.status).toBe("READY");expect(store).toHaveBeenCalledOnce()});
});
