import {describe,expect,it,vi} from "vitest";
import {planAccount} from "../auto/engine";
import {GOOGLE_FLOW_MANUAL,GOOGLE_VEO_MODELS,GoogleVeoProvider,GoogleVeoProviderError,generateAcceptedGoogleVeoMaster} from "./google-veo";
import {createVideoCostPlan,rankVideoProviders,selectVideoProvider,type ProviderEvidence} from "./provider-routing";
import {CostRouter} from "./cost-router";
import type {RenderedVideo,VideoQualityInput} from "./types";

const key="test-google-key-never-log-123456",json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}}),video=()=>new Response(new Uint8Array([0,1,2,3]),{status:200,headers:{"content-type":"video/mp4"}}),done={name:"operations/ok",done:true,response:{generateVideoResponse:{generatedSamples:[{video:{uri:"https://example.invalid/video.mp4"}}]}}};
const fetchSequence=(...responses:Response[])=>vi.fn(async()=>responses.shift()??json({error:{message:"Unexpected mock request"}},500)) as unknown as typeof fetch;
const provider=(responses:Response[],options:Partial<ConstructorParameters<typeof GoogleVeoProvider>[0]>={})=>new GoogleVeoProvider({apiKey:key,fetchImpl:fetchSequence(...responses),sleep:async()=>{},pollIntervalMs:0,maxPollAttempts:3,...options});
const request={prompt:"Commercial portrait product shot",durationSeconds:8 as const,aspectRatio:"9:16" as const,resolution:"720p" as const,maxCostUsd:.4};
const media:RenderedVideo={path:"memory.mp4",duration:8,width:720,height:1280,fps:24,videoCodec:"h264",audioCodec:"aac",hasAudio:true,sizeBytes:1000};
const qualityInput=(value:RenderedVideo):VideoQualityInput=>({...value,overlay:[],scenes:[],productVisible:true,ctaVisible:true,malformedAssets:false,inheritedRisk:"SAFE"});
const account={id:"a",requestedMode:"AUTO" as const,commerceReady:false,providerAvailable:true,analyticsFresh:true,accountHealthy:true,consent:true,publishRemaining:3,desiredCandidates:3,desiredPosts:2,priority:50};

describe("GoogleVeoProvider",()=>{
  it("reports availability without exposing the key",()=>{expect(new GoogleVeoProvider().isAvailable()).toBe(false);expect(provider([]).isAvailable()).toBe(true)});
  it("maps Lite, Fast, and Standard to current official model names",()=>expect(Object.values(GOOGLE_VEO_MODELS).map(x=>x.apiModel)).toEqual(["veo-3.1-lite-generate-preview","veo-3.1-fast-generate-preview","veo-3.1-generate-preview"]));
  it("estimates 8-second 720p costs",()=>{expect(new GoogleVeoProvider({model:"VEO_3_1_LITE"}).estimateCost(request)).toBe(.4);expect(new GoogleVeoProvider({model:"VEO_3_1_FAST"}).estimateCost(request)).toBe(.8);expect(new GoogleVeoProvider({model:"VEO_3_1_STANDARD"}).estimateCost(request)).toBe(3.2)});
  it("exposes image/text, duration, aspect, fps and audio capabilities",()=>expect(new GoogleVeoProvider().getCapabilities()).toMatchObject({textToVideo:true,imageToVideo:true,durations:[4,6,8],aspectRatios:["9:16","16:9"],fps:24,audio:"ALWAYS_ON"}));
  it("generates, polls, downloads, and normalizes a successful result",async()=>{const result=await provider([json({name:"operations/ok"}),json(done),video()]).generate(request);expect(result).toMatchObject({operationName:"operations/ok",actualCostUsd:.4,retryCount:0,checksum:expect.stringMatching(/^[a-f0-9]{64}$/)});expect(result.bytes).toHaveLength(4)});
  it("polls a pending operation before completion",async()=>{const result=await provider([json({name:"operations/ok"}),json({name:"operations/ok",done:false}),json(done),video()]).generate(request);expect(result.operationName).toBe("operations/ok")});
  it("maps failed operations",async()=>{await expect(provider([json({name:"operations/fail"}),json({name:"operations/fail",done:true,error:{code:400,message:"operation failed"}})]).generate(request)).rejects.toMatchObject({code:"OPERATION_FAILED"})});
  it("times out with bounded polling",async()=>{await expect(provider([json({name:"operations/slow"}),json({name:"operations/slow",done:false}),json({name:"operations/slow",done:false}),json({name:"operations/slow",done:false})]).generate(request)).rejects.toMatchObject({code:"TIMEOUT"})});
  it("blocks spend before making a request",async()=>{const fetchImpl=fetchSequence();const client=new GoogleVeoProvider({apiKey:key,fetchImpl});await expect(client.generate({...request,maxCostUsd:.39})).rejects.toMatchObject({code:"BUDGET_EXCEEDED"});expect(fetchImpl).not.toHaveBeenCalled()});
  it("retries rate-limited polling within the configured bound",async()=>{const result=await provider([json({name:"operations/retry"}),json({error:{message:"rate limited"}},429),json({...done,name:"operations/retry"}),video()]).generate(request);expect(result.retryCount).toBe(1)});
  it("classifies exhausted quota",async()=>{await expect(provider([json({error:{message:"quota exceeded",status:"RESOURCE_EXHAUSTED"}},429)]).generate(request)).rejects.toMatchObject({code:"QUOTA_EXCEEDED",retryable:true})});
  it("rejects a completed operation without output",async()=>{await expect(provider([json({name:"operations/empty"}),json({name:"operations/empty",done:true,response:{}})]).generate(request)).rejects.toMatchObject({code:"INVALID_OUTPUT"})});
  it("records successful-generation cost when output download fails",async()=>{await expect(provider([json({name:"operations/download"}),json({...done,name:"operations/download"}),json({error:{message:"gone"}},404)]).generate(request)).rejects.toMatchObject({code:"DOWNLOAD_FAILED",actualCostUsd:.4})});
  it("maps moderation failures to safety rejection",async()=>{await expect(provider([json({name:"operations/safe"}),json({name:"operations/safe",done:true,error:{code:400,message:"Blocked by safety filter"}})]).generate(request)).rejects.toMatchObject({code:"SAFETY_REJECTED"})});
  it("never includes the API key in a normalized failure",()=>{const client=provider([]),failure=client.getFailureReason(new Error(`request ${key} failed`));expect(failure.message).not.toContain(key);expect(failure.message).toContain("[REDACTED]")});
});

describe("Google Veo master, router, Auto Mode, and cost plans",()=>{
  it("rejects provider output below the quality gate",async()=>{const client=provider([json({name:"operations/ok"}),json(done),video()]);await expect(generateAcceptedGoogleVeoMaster({provider:client,request,inspect:async()=>media,qualityInput,evaluate:()=>({score:84,status:"RETRY",explanation:{}}),store:async()=>"never"})).rejects.toBeInstanceOf(GoogleVeoProviderError)});
  it("stores a successful master only after quality passes",async()=>{const store=vi.fn(async()=>"owner/id/masters/m/provider-original.mp4"),client=provider([json({name:"operations/ok"}),json(done),video()]),result=await generateAcceptedGoogleVeoMaster({provider:client,request,inspect:async()=>media,qualityInput,evaluate:()=>({score:92,status:"PASS",explanation:{}}),store});expect(result).toMatchObject({status:"READY",storagePath:"owner/id/masters/m/provider-original.mp4"});expect(store).toHaveBeenCalledOnce()});
  it("keeps Google Flow manual-only",()=>expect(GOOGLE_FLOW_MANUAL).toEqual({provider:"GOOGLE_FLOW_MANUAL",status:"MANUAL_BENCHMARK_ONLY",automated:false}));
  it("selects by quality, reliability, and retry-adjusted cost",()=>{const rows:ProviderEvidence[]=[{provider:"google-veo-lite",model:"lite",available:true,automated:true,qualityScore:90,humanStatus:"FLOW_COMPARABLE",successRate:.8,nominalCostUsd:.4,samples:3},{provider:"fal-wan-2.2-turbo",model:"wan",available:true,automated:true,qualityScore:88,humanStatus:"FLOW_COMPARABLE",successRate:.9,nominalCostUsd:.1,samples:3}];expect(selectVideoProvider(rows)?.provider).toBe("fal-wan-2.2-turbo");expect(rankVideoProviders(rows)[0]?.selectionScore).toBeGreaterThan(0);expect(new CostRouter().chooseProvider(rows,{maxCostPerVideoUsd:1,dailyVideoBudgetUsd:10,monthlyVideoBudgetUsd:100,spentTodayUsd:0,spentMonthUsd:0})?.provider).toBe("fal-wan-2.2-turbo")});
  it("does not route unbenchmarked providers",()=>expect(selectVideoProvider([{provider:"google-veo-lite",model:"lite",available:true,automated:true,qualityScore:null,humanStatus:null,successRate:1,nominalCostUsd:.4,samples:0}])).toBeNull());
  it("puts Auto Mode in WAITING_FOR_PROVIDER without a key-backed provider",()=>expect(planAccount({...account,providerAvailable:false}).state).toBe("WAITING_FOR_PROVIDER"));
  it("blocks Auto Mode on exhausted or unset provider budget",()=>expect(planAccount({...account,providerBudgetAvailable:false})).toMatchObject({state:"BLOCKED",nextAction:"WAIT_FOR_BUDGET",blockers:["BUDGET_EXCEEDED"]}));
  it("models the 3-account 15–20 master plan",()=>{const plan=createVideoCostPlan("CURRENT_3_ACCOUNTS"),lite=plan.providers.find(x=>x.provider==="google-veo-lite");expect(plan).toMatchObject({accounts:3,mastersPerDay:[15,20],finalsPerDay:[45,60],aiGenerationsPerMonth:[450,600]});expect(lite).toMatchObject({nominalMonthlyUsd:[180,240],retryAdjustedMonthlyUsd:[211.7647,282.3529]})});
  it("models the 10-account 40–50 master plan",()=>{const plan=createVideoCostPlan("FUTURE_10_ACCOUNTS"),lite=plan.providers.find(x=>x.provider==="google-veo-lite");expect(plan).toMatchObject({accounts:10,mastersPerDay:[40,50],finalsPerDay:[150,150],aiGenerationsPerMonth:[1200,1500]});expect(lite).toMatchObject({nominalMonthlyUsd:[480,600],retryAdjustedMonthlyUsd:[564.7059,705.8824]})});
});
