import type {HumanQualityStatus} from "../video-benchmark/types";

export type AutomatedVideoProvider="google-veo-lite"|"google-veo-fast"|"google-veo-standard"|"fal-wan-2.2-turbo"|"pixverse-v6"|"runway-gen4-turbo";
export interface ProviderEvidence {provider:AutomatedVideoProvider;model:string;available:boolean;automated:boolean;qualityScore:number|null;humanStatus:HumanQualityStatus|null;successRate:number;nominalCostUsd:number;samples:number}
export interface RankedProvider extends ProviderEvidence {retryAdjustedCostUsd:number;selectionScore:number;eligible:boolean;reason:string}

export function rankVideoProviders(candidates:ProviderEvidence[],qualityThreshold=85){return candidates.map(candidate=>{const retryAdjustedCostUsd=candidate.successRate>0?candidate.nominalCostUsd/candidate.successRate:Number.POSITIVE_INFINITY,quality=candidate.qualityScore??0,eligible=candidate.available&&candidate.automated&&candidate.samples>0&&quality>=qualityThreshold&&candidate.humanStatus!=="BELOW_FLOW"&&candidate.humanStatus!==null&&candidate.successRate>0,selectionScore=eligible?Number(((quality/100)*candidate.successRate/Math.max(retryAdjustedCostUsd,.000001)).toFixed(6)):0;return{...candidate,retryAdjustedCostUsd:Number.isFinite(retryAdjustedCostUsd)?Number(retryAdjustedCostUsd.toFixed(6)):retryAdjustedCostUsd,selectionScore,eligible,reason:!candidate.available?"Provider unavailable":!candidate.automated?"Manual provider cannot run in Auto Mode":candidate.samples<1?"Benchmark evidence required":quality<qualityThreshold?"Technical quality threshold not met":candidate.humanStatus===null?"Owner Flow comparison required":candidate.humanStatus==="BELOW_FLOW"?"Below owner Flow reference":candidate.successRate<=0?"No successful generations":"Eligible by quality, reliability, and retry-adjusted cost"}}).toSorted((a,b)=>b.selectionScore-a.selectionScore||a.retryAdjustedCostUsd-b.retryAdjustedCostUsd)}
export function selectVideoProvider(candidates:ProviderEvidence[],qualityThreshold=85){return rankVideoProviders(candidates,qualityThreshold).find(candidate=>candidate.eligible)??null}

export const VIDEO_COST_CATALOG={
  "google-veo-lite":{label:"Google Veo 3.1 Lite",model:"veo-3.1-lite-generate-preview",costPerEightSecondsUsd:.40,planningSuccessRate:.85},
  "google-veo-fast":{label:"Google Veo 3.1 Fast",model:"veo-3.1-fast-generate-preview",costPerEightSecondsUsd:.80,planningSuccessRate:.85},
  "google-veo-standard":{label:"Google Veo 3.1 Standard",model:"veo-3.1-generate-preview",costPerEightSecondsUsd:3.20,planningSuccessRate:.85},
  "fal-wan-2.2-turbo":{label:"fal Wan 2.2 Turbo",model:"fal-ai/wan/v2.2-a14b/image-to-video/turbo",costPerEightSecondsUsd:.10,planningSuccessRate:.85},
  "pixverse-v6":{label:"PixVerse V6",model:"v6",costPerEightSecondsUsd:.72,planningSuccessRate:.85},
  "runway-gen4-turbo":{label:"Runway Gen-4 Turbo",model:"gen4_turbo",costPerEightSecondsUsd:.40,planningSuccessRate:.85},
} as const;

export type CostPlanScale="CURRENT_3_ACCOUNTS"|"FUTURE_10_ACCOUNTS";
export interface VideoCostPlan {scale:CostPlanScale;accounts:number;mastersPerDay:[number,number];finalsPerDay:[number,number];aiGenerationsPerMonth:[number,number];providers:Array<{provider:AutomatedVideoProvider;label:string;nominalMonthlyUsd:[number,number];retryAdjustedMonthlyUsd:[number,number];nominalCostPerFinalUsd:[number,number];retryAdjustedCostPerFinalUsd:[number,number];assumedSuccessRate:number}>}
const round=(value:number)=>Number(value.toFixed(4));
export function createVideoCostPlan(scale:CostPlanScale):VideoCostPlan{const current=scale==="CURRENT_3_ACCOUNTS",accounts=current?3:10,mastersPerDay:[number,number]=current?[15,20]:[40,50],finalsPerDay:[number,number]=current?[45,60]:[150,150],aiGenerationsPerMonth:[number,number]=[mastersPerDay[0]*30,mastersPerDay[1]*30],finalsPerMonth:[number,number]=[finalsPerDay[0]*30,finalsPerDay[1]*30];return{scale,accounts,mastersPerDay,finalsPerDay,aiGenerationsPerMonth,providers:Object.entries(VIDEO_COST_CATALOG).map(([provider,item])=>{const nominal:[number,number]=[round(aiGenerationsPerMonth[0]*item.costPerEightSecondsUsd),round(aiGenerationsPerMonth[1]*item.costPerEightSecondsUsd)],adjusted:[number,number]=[round(nominal[0]/item.planningSuccessRate),round(nominal[1]/item.planningSuccessRate)];return{provider:provider as AutomatedVideoProvider,label:item.label,nominalMonthlyUsd:nominal,retryAdjustedMonthlyUsd:adjusted,nominalCostPerFinalUsd:[round(nominal[0]/finalsPerMonth[1]),round(nominal[1]/finalsPerMonth[0])],retryAdjustedCostPerFinalUsd:[round(adjusted[0]/finalsPerMonth[1]),round(adjusted[1]/finalsPerMonth[0])],assumedSuccessRate:item.planningSuccessRate}})}}
