import {createHash} from "node:crypto";
import {CostRouter} from "../video/cost-router";
import type {AccountContext,AutoState,BudgetContext,EffectiveAutoMode,FailureType,GateInput,PlannedAccount,SafetyGate} from "./types";
export const AUTO_VERSION="auto-orchestration-v1";
const costRouter=new CostRouter();
export function stableAutoKey(...parts:Array<string|number>){return createHash("sha256").update(parts.join(":" )).digest("hex")}
export function resolveAutoMode(requested:"GROWTH"|"AFFILIATE"|"AUTO",commerceReady:boolean):EffectiveAutoMode{return requested==="GROWTH"?"GROWTH":requested==="AFFILIATE"&&commerceReady?"AFFILIATE":requested==="AUTO"&&commerceReady?"AFFILIATE":"GROWTH"}
export function startAutoMode(state:AutoState){return ["IDLE","COMPLETED","FAILED","STOPPED"].includes(state)?"STARTING":state}
export function pauseAutoMode(state:AutoState){return ["RUNNING","RETRY_PENDING","WAITING_FOR_DATA","WAITING_FOR_SLOT","WAITING_FOR_PROVIDER"].includes(state)?"PAUSED":state}
export function resumeAutoMode(state:AutoState){return state==="PAUSED"?"RUNNING":state}
export function stopAutoMode(state:AutoState){return ["COMPLETED","FAILED","STOPPED"].includes(state)?state:"STOPPED"}
export function checkBudget(b:BudgetContext){const existingAllowed=costRouter.canSpend({maxCostPerVideoUsd:b.perVideoBudget,dailyVideoBudgetUsd:b.dailyBudget,monthlyVideoBudgetUsd:b.monthlyBudget,spentTodayUsd:b.dailySpent,spentMonthUsd:b.monthlySpent},b.estimated),limits=[existingAllowed,b.runSpent+b.estimated<=b.runBudget,b.accountSpent+b.estimated<=b.accountBudget,b.providerSpent+b.estimated<=b.providerBudget];return{allowed:limits.every(Boolean),blocker:limits.every(Boolean)?null:"BUDGET_EXCEEDED" as const}}
export function evaluateSafetyGates(input:GateInput){const checks:Record<SafetyGate,boolean>={QUALITY:input.quality,COMPLIANCE:input.compliance,PRODUCT_TRUTH:input.mode==="GROWTH"||input.productTruth,AIGC:input.aigc,ORIGINALITY:input.originality,CROSS_ACCOUNT_DUPLICATION:input.crossAccountUnique,ACCOUNT_HEALTH:input.accountHealth,COMMERCE:input.mode==="GROWTH"||input.commerceReady,PUBLISH_CAP:input.publishCapacity,CONSENT:input.consent};const blockers=Object.entries(checks).filter(([,pass])=>!pass).map(([gate])=>gate as SafetyGate);return{passed:blockers.length===0,blockers,nextState:blockers.includes("CONSENT")?"WAITING_FOR_APPROVAL":blockers.includes("PUBLISH_CAP")?"WAITING_FOR_SLOT":"BLOCKED" as AutoState}}
export function classifyFailure(message:string):{type:FailureType;retryable:boolean;maxRetries:number}{const value=message.toLowerCase();if(/timeout|network|429|temporary/.test(value))return{type:"TRANSIENT",retryable:true,maxRetries:3};if(/token|permission|scope|auth/.test(value))return{type:"PERMISSION",retryable:false,maxRetries:0};if(/budget|cost/.test(value))return{type:"BUDGET",retryable:false,maxRetries:0};if(/provider/.test(value))return{type:"PROVIDER",retryable:true,maxRetries:2};if(/compliance|claim|originality/.test(value))return{type:"COMPLIANCE",retryable:false,maxRetries:0};if(/publish/.test(value))return{type:"PUBLISH",retryable:true,maxRetries:2};if(/analytics/.test(value))return{type:"ANALYTICS",retryable:true,maxRetries:3};return{type:"UNKNOWN",retryable:false,maxRetries:0}}
export function retryState(retryCount:number,maxRetries:number){return retryCount<maxRetries?"RETRY_PENDING":"FAILED"}
export function recoverFromCheckpoint(checkpoints:Array<{version:number;step:string;state:Record<string,unknown>}>){return checkpoints.toSorted((a,b)=>b.version-a.version)[0]??null}
export function controlledVariation(decision:string,capacity:number,costAllowed:boolean){if(!["SCALE","SCALE_HOOK","SCALE_ANGLE","SCALE_PRODUCT","SCALE_CREATIVE"].includes(decision)||capacity<1||!costAllowed)return null;return{axis:decision.includes("HOOK")?"HOOK":decision.includes("ANGLE")?"ANGLE":"SCENE",originalityRequired:true,action:"CREATE_VARIATION"}}
export function planAccount(input:AccountContext):PlannedAccount{const mode=resolveAutoMode(input.requestedMode,input.commerceReady),publishCapacity=Math.max(0,Math.min(input.publishRemaining,input.desiredPosts)),generationCapacity=Math.max(0,input.desiredCandidates);if(!input.accountHealthy)return{accountId:input.id,mode,state:"BLOCKED",nextAction:"WAIT_FOR_ACCOUNT",blockers:["ACCOUNT_HEALTH"],generationCapacity:0,publishCapacity:0};if(!input.providerAvailable)return{accountId:input.id,mode,state:"WAITING_FOR_PROVIDER",nextAction:"WAIT_FOR_PROVIDER",blockers:["PROVIDER_UNAVAILABLE"],generationCapacity:0,publishCapacity};if(input.providerBudgetAvailable===false)return{accountId:input.id,mode,state:"BLOCKED",nextAction:"WAIT_FOR_BUDGET",blockers:["BUDGET_EXCEEDED"],generationCapacity:0,publishCapacity};if(!input.analyticsFresh)return{accountId:input.id,mode,state:"WAITING_FOR_DATA",nextAction:"SYNC_ANALYTICS",blockers:["ANALYTICS_STALE"],generationCapacity,publishCapacity};if(publishCapacity===0)return{accountId:input.id,mode,state:"WAITING_FOR_SLOT",nextAction:"QUEUE_NEXT_DAY",blockers:["PUBLISH_CAP"],generationCapacity,publishCapacity};if(!input.consent)return{accountId:input.id,mode,state:"WAITING_FOR_APPROVAL",nextAction:"REQUEST_APPROVAL",blockers:["CONSENT"],generationCapacity,publishCapacity};const nextAction=mode==="GROWTH"?(input.nextGrowthAction??"WAIT_FOR_DATA"):(input.affiliateDecision==="SCALE"?"SCALE_PRODUCT":input.affiliateDecision??"WATCH");return{accountId:input.id,mode,state:"RUNNING",nextAction,blockers:[],generationCapacity,publishCapacity}}
