import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {z} from "zod";
import {PageHeading} from "@/components/page-heading";
import {CategoryStateBadge,number} from "@/components/category-presentation";
import {ProductImage,money} from "@/components/product-presentation";
import {createClient} from "@/lib/supabase/server";
import {getCategoryDetail} from "@/features/categories/services";
export default async function CategoryDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;if(!z.uuid().safeParse(id).success)notFound();const client=await createClient();const {data}=await client.auth.getUser();if(!data.user)redirect("/login");const result=await getCategoryDetail(client,data.user.id,id);if(!result)notFound();const {category,snapshot,score,products,fits,snapshotHistory}=result;const top=products.toSorted((a,b)=>(b.score?.product_momentum_score??0)-(a.score?.product_momentum_score??0));return <>
 <PageHeading eyebrow="CATEGORY DETAIL" title={category.display_name} description={`${category.category_key} · ${category.provider}`} action={<Link className="secondary-action" href="/categories">← กลับ Category Radar</Link>}/>
 <section className="stats-grid"><article className="stat-card green"><p>State</p><CategoryStateBadge state={score.state}/><small>{score.score_version}</small></article><article className="stat-card blue"><p>Momentum</p><strong>{number(score.category_momentum_score)}</strong><small>robust breadth + current velocity</small></article><article className="stat-card amber"><p>Commercial</p><strong>{number(score.commercial_opportunity_score)}</strong><small>affiliate economics adjusted</small></article><article className="stat-card violet"><p>Confidence</p><strong>{number(snapshot.data_confidence*100)}%</strong><small>{snapshot.product_count} products</small></article></section>
 <section className="panel radar-section"><div className="panel-heading"><h2>Score breakdown</h2><span className="phase-chip">{score.score_version}</span></div><div className="score-breakdown">{Object.entries(score.explanation_json.signals).map(([key,signal])=><article key={key}><div><strong>{key}</strong><b>{number(signal.score)}</b></div><meter min={0} max={100} value={signal.score}/><p>{signal.reason}</p></article>)}</div></section>
 <section className="detail-summary-grid"><article className="panel"><h2>Product distribution</h2><dl className="detail-list"><div><dt>Active</dt><dd>{snapshot.active_product_count}</dd></div><div><dt>Accelerating / Rising</dt><dd>{snapshot.accelerating_product_count} / {snapshot.rising_product_count}</dd></div><div><dt>Falling</dt><dd>{snapshot.falling_product_count}</dd></div><div><dt>Median / top quartile</dt><dd>{number(snapshot.median_product_momentum)} / {number(snapshot.top_quartile_momentum)}</dd></div><div><dt>Competition / saturation</dt><dd>{number(snapshot.competition_signal*100)}% / {number(snapshot.saturation_signal*100)}%</dd></div></dl></article><article className="panel"><h2>Best accounts & affinity</h2><div className="data-list">{fits.map(f=><div key={f.account.id}><strong>{f.account.display_name}</strong><span>{number(f.score)} fit</span><small>{f.account.effective_mode} · affinity {f.affinity?number(Number(f.affinity.affinity_score)*100)+"%":"neutral"} · confidence {number(f.confidence*100)}%</small></div>)}</div></article></section>
 <section className="panel radar-section"><h2>Top, rising and falling products</h2><div className="radar-table-wrap"><table className="radar-table"><thead><tr><th>Product</th><th>Price</th><th>Momentum</th><th>Trend</th></tr></thead><tbody>{top.map(({product:p,score:s})=><tr key={p.id}><td><Link className="radar-product" href={`/product-radar/${p.id}`}><ProductImage url={p.image_url} title={p.title}/><strong>{p.title}</strong></Link></td><td>{money(p.current_price)}</td><td>{s?number(s.product_momentum_score):"—"}</td><td>{s?.explanation_json.trend??"LOW_DATA"}</td></tr>)}</tbody></table></div></section>
 <section className="panel radar-section"><h2>Historical snapshots</h2><div className="data-list">{snapshotHistory.map((s,i)=><div key={s.id??i}><strong>{new Date(s.captured_at).toLocaleString("th-TH",{timeZone:"Asia/Bangkok"})}</strong><span>{number(s.median_product_momentum)} median</span><small>velocity {number(s.sales_velocity)} · acceleration {number(s.sales_acceleration,2)} · confidence {number(s.data_confidence*100)}%</small></div>)}</div></section>
 </>}
