import {describe,expect,it} from "vitest";
import {analyticsFixtures} from "./fixtures";
import {boundedAdjustment,combineAccountSignals,decayedSignal,proposeControlledVariation} from "./learning";
import {MockTikTokAnalyticsProvider,TikTokAnalyticsProvider,TikTokShopAnalyticsProvider} from "./provider";
import {calculateWinner,deriveAccountBaseline,evidenceHash,normalizeMetrics} from "./scoring";

describe("Phase 8 analytics and learning",()=>{
 it("preserves unavailable metrics as null and never converts zero views into a rate",()=>{expect(normalizeMetrics({...analyticsFixtures.F,views:0}).conversionRate).toBeNull();expect(normalizeMetrics({...analyticsFixtures.F,favorites:null}).favoriteRate).toBeNull();});
 it("classifies deterministic fixtures A-J",()=>{const r=Object.fromEntries(Object.entries(analyticsFixtures).map(([k,v])=>[k,calculateWinner(v)]));expect(r.A.decision).toBe("SCALE");expect(r.B.decision).toBe("STOP");expect(r.C.decision).toBe("SCALE");expect(r.D.decision).toBe("STOP");expect(r.E.decision).toBe("INSUFFICIENT_DATA");expect(r.F.decision).toBe("INSUFFICIENT_DATA");expect(r.G.finalScore).not.toBeNull();expect(r.H.decision).not.toBe("SCALE");expect(r.I.finalScore!).toBeGreaterThan(r.H.finalScore!);expect(r.J.finalScore!).toBeLessThan(r.A.finalScore!);});
 it("supports delayed affiliate attribution as new immutable evidence",()=>{const early=calculateWinner(analyticsFixtures.H),late=calculateWinner(analyticsFixtures.I);expect(evidenceHash(analyticsFixtures.H)).not.toBe(evidenceHash(analyticsFixtures.I));expect(late.finalScore!).toBeGreaterThan(early.finalScore!);});
 it("derives a robust account-only median baseline",()=>{const baseline=deriveAccountBaseline([analyticsFixtures.B,analyticsFixtures.A,analyticsFixtures.G]);expect(baseline.views).toBe(1200);expect(baseline.engagementRate).toBeGreaterThan(0);});
 it("creates one-axis variations only for confident winners and keeps originality mandatory",()=>{const result=calculateWinner(analyticsFixtures.A);const a=proposeControlledVariation({ownerId:"o",accountId:"a",videoId:"v",result,axis:"HOOK",controlValue:"h1",variantValue:"h2"});const b=proposeControlledVariation({ownerId:"o",accountId:"a",videoId:"v",result,axis:"HOOK",controlValue:"h1",variantValue:"h2"});expect(a).toEqual(b);expect(a?.originalityRequired).toBe(true);expect(proposeControlledVariation({ownerId:"o",accountId:"a",videoId:"v",result:{...result,decision:"WATCH"},axis:"HOOK",controlValue:"h1",variantValue:"h2"})).toBeNull();});
 it("bounds, decays and isolates learning signals",()=>{expect(boundedAdjustment(1,1,1)).toBe(.2);expect(decayedSignal(1,14)).toBeCloseTo(.5);expect(combineAccountSignals([{effect:1,confidence:1,decay:1,sampleSize:20},{effect:-1,confidence:.1,decay:.5,sampleSize:1}])).toBeGreaterThan(.8);});
 it("keeps real providers disabled and mock deterministic",async()=>{expect(new TikTokAnalyticsProvider().isAvailable()).toBe(false);expect(new TikTokShopAnalyticsProvider().isAvailable()).toBe(false);const p=new MockTikTokAnalyticsProvider([]);expect(await p.fetchVideoAnalytics("x")).toEqual([]);});
 it("handles the 10 accounts × 150 published/day × 30 days envelope",()=>{let scale=0;for(let account=0;account<10;account+=1)for(let day=0;day<30;day+=1)for(let video=0;video<150;video+=1){if(calculateWinner({...analyticsFixtures.A,id:`${account}-${day}-${video}`,accountId:`a-${account}`}).decision==="SCALE")scale+=1;}expect(scale).toBe(45_000);});
});
