import type {SupabaseClient} from "@supabase/supabase-js";
import type {AnalyticsSummary,LearningSignalRow,VideoSnapshotRow,WinnerRow} from "./types";
import type {WinnerResult} from "./types";
import type {VideoAnalyticsObservation} from "./provider";
import {evidenceHash} from "./scoring";

async function read<T>(client:SupabaseClient,table:string,ownerId:string,limit=500){const {data,error}=await client.from(table).select("*").eq("owner_id",ownerId).order("created_at",{ascending:false}).limit(limit);if(error)throw new Error(`Analytics query failed: ${error.message}`);return(data??[]) as T[];}
export async function getAnalyticsOverview(client:SupabaseClient,ownerId:string){
 const [scores,snapshots,accounts,products]=await Promise.all([read<WinnerRow>(client,"winner_scores",ownerId),read<VideoSnapshotRow>(client,"video_analytics_snapshots",ownerId),client.from("tiktok_accounts").select("id,display_name,effective_mode").eq("owner_id",ownerId),client.from("products").select("id,title").eq("owner_id",ownerId)]);
 if(accounts.error)throw new Error(accounts.error.message);if(products.error)throw new Error(products.error.message);
 const latest=new Map<string,WinnerRow>();for(const row of scores)if(!latest.has(`${row.video_kind}:${row.video_id}`))latest.set(`${row.video_kind}:${row.video_id}`,row);
 const winners=[...latest.values()];const summary:AnalyticsSummary={totalVideos:winners.length,scale:winners.filter(x=>x.decision==="SCALE").length,watch:winners.filter(x=>x.decision==="WATCH").length,stop:winners.filter(x=>x.decision==="STOP").length,insufficient:winners.filter(x=>x.decision==="INSUFFICIENT_DATA").length,views:snapshots.reduce((s,x)=>s+(x.views??0),0),orders:snapshots.reduce((s,x)=>s+(x.orders??0),0),gmv:snapshots.reduce((s,x)=>s+(x.gmv??0),0),commission:snapshots.reduce((s,x)=>s+(x.commission??0),0)};
 return{summary,winners,snapshots,accounts:(accounts.data??[]) as Array<{id:string;display_name:string;effective_mode:string}>,products:(products.data??[]) as Array<{id:string;title:string}>};
}
export async function getAccountAnalytics(client:SupabaseClient,ownerId:string,id:string){const overview=await getAnalyticsOverview(client,ownerId);const account=overview.accounts.find(x=>x.id===id);if(!account)return null;return{account,winners:overview.winners.filter(x=>x.tiktok_account_id===id),snapshots:overview.snapshots.filter(x=>x.tiktok_account_id===id)};}
export async function getVideoAnalytics(client:SupabaseClient,ownerId:string,id:string){const overview=await getAnalyticsOverview(client,ownerId);const snapshots=overview.snapshots.filter(x=>x.video_id===id);if(!snapshots.length)return null;return{snapshots,winners:overview.winners.filter(x=>x.video_id===id)};}
export async function getProductAnalytics(client:SupabaseClient,ownerId:string,id:string){const overview=await getAnalyticsOverview(client,ownerId);const product=overview.products.find(x=>x.id===id);if(!product)return null;return{product,snapshots:overview.snapshots.filter(x=>x.product_id===id)};}
export async function getLearningOverview(client:SupabaseClient,ownerId:string){const [signals,decisions,experiments]=await Promise.all([read<LearningSignalRow>(client,"learning_signals",ownerId),read<Record<string,unknown>>(client,"learning_decisions",ownerId),read<Record<string,unknown>>(client,"experiment_variants",ownerId)]);return{signals,decisions,experiments};}

export async function persistVideoEvaluation(admin:SupabaseClient,input:{ownerId:string;accountId:string;videoId:string;videoKind:"MASTER"|"VARIATION"|"EXTERNAL";mode:"GROWTH"|"AFFILIATE";observation:VideoAnalyticsObservation;result:WinnerResult;baseline:Record<string,number>;productId?:string|null}){
 const {externalVideoId,capturedAt,sourceConfidence,...metrics}=input.observation;
 const snapshotValues={owner_id:input.ownerId,tiktok_account_id:input.accountId,video_id:input.videoId,video_kind:input.videoKind,external_video_id:externalVideoId,product_id:input.productId??null,source_snapshot_at:capturedAt,...metrics,source_confidence:sourceConfidence,availability_json:{favorites:input.observation.favorites===null?"UNKNOWN":"AVAILABLE",commerce:input.observation.orders===null?"UNKNOWN":"AVAILABLE"},raw_metadata_json:{}};
 const inserted=await admin.from("video_analytics_snapshots").insert(snapshotValues).select("id").maybeSingle();
 let snapshot=inserted.data;if(inserted.error?.code==="23505"){const existing=await admin.from("video_analytics_snapshots").select("id").eq("owner_id",input.ownerId).eq("source",input.observation.source).eq("external_video_id",input.observation.externalVideoId).eq("source_snapshot_at",input.observation.capturedAt).single();if(existing.error)throw new Error(existing.error.message);snapshot=existing.data;}else if(inserted.error)throw new Error(inserted.error.message);if(!snapshot)throw new Error("analytics_snapshot_missing");
 const hash=evidenceHash({snapshotId:snapshot.id,mode:input.mode,result:input.result});const scoreValues={owner_id:input.ownerId,tiktok_account_id:input.accountId,video_snapshot_id:snapshot.id,video_id:input.videoId,video_kind:input.videoKind,mode:input.mode,growth_score:input.result.growthScore,affiliate_score:input.result.affiliateScore,final_score:input.result.finalScore,decision:input.result.decision,confidence:input.result.confidence,sample_factor:input.result.sampleFactor,freshness_factor:input.result.freshnessFactor,account_baseline_json:input.baseline,components_json:input.result.components,explanation_json:{relativeTo:"ACCOUNT_BASELINE"},evidence_hash:hash,evaluated_at:new Date().toISOString()};
 const scored=await admin.from("winner_scores").insert(scoreValues).select("id").maybeSingle();if(scored.error?.code==="23505"){const existing=await admin.from("winner_scores").select("id").eq("owner_id",input.ownerId).eq("video_id",input.videoId).eq("video_kind",input.videoKind).eq("score_version","winner-detection-v1").eq("evidence_hash",hash).single();if(existing.error)throw new Error(existing.error.message);return{snapshotId:snapshot.id,winnerScoreId:existing.data.id,duplicate:true};}if(scored.error)throw new Error(scored.error.message);return{snapshotId:snapshot.id,winnerScoreId:scored.data!.id,duplicate:false};
}
