import {describe,expect,it} from "vitest";import {accountPatternFixtures,commerceFixtures,growthFixtures} from "./fixtures";import {calculateFollowerEfficiency,calculateGrowthOptimizationScore,growthFreshness} from "./scoring";import {allocateExploreExploit,buildGrowthRecommendation,growthPublishingAllowed,learnAccountPatterns,milestoneTransition,planGrowthExperiment,recommendCategories,resolveGrowthState} from "./strategy";
import {growthEvidenceHash} from "./persistence";
describe("Phase 9 Growth Learning Engine",()=>{
 it("calculates follower delta efficiency without inventing missing attribution",()=>{const known=calculateFollowerEfficiency({followerDelta:20,views:4000,videos:2,followersStart:500,days:2,previousRollingRate:8,attributionConfidence:.6});expect(known.followersPer1000Views).toBe(5);expect(known.followersPerVideo).toBe(10);expect(known.growthRate).toBe(.04);expect(known.rollingGrowthRate).toBe(9.2);const missing=calculateFollowerEfficiency({followerDelta:null,views:4000,videos:2,followersStart:500,days:2,previousRollingRate:8,attributionConfidence:1});expect(missing.followersPer1000Views).toBeNull();expect(missing.attributionConfidence).toBe(0);});
 it("scores A-D with sample and follower-efficiency controls",()=>{expect(calculateGrowthOptimizationScore(growthFixtures.A).decision).toBe("INSUFFICIENT_DATA");expect(calculateGrowthOptimizationScore(growthFixtures.B).score).not.toBeNull();expect(calculateGrowthOptimizationScore(growthFixtures.C).components.followerEfficiency).toBe(0);expect(calculateGrowthOptimizationScore(growthFixtures.D).score!).toBeGreaterThan(calculateGrowthOptimizationScore(growthFixtures.B).score!);});
 it("keeps hook learning account specific",()=>{const a=learnAccountPatterns("A",accountPatternFixtures).find(x=>x.value==="question")!,b=learnAccountPatterns("B",accountPatternFixtures).find(x=>x.value==="question")!;expect(a.state).toBe("WINNING");expect(b.state).toBe("WEAK");expect(a.score).toBeGreaterThan(b.score);});
 it("applies confidence and time decay",()=>{expect(growthFreshness(24*60)).toBeLessThan(growthFreshness(24));const old=learnAccountPatterns("A",accountPatternFixtures).find(x=>x.value==="old-winner")!;expect(old.confidence).toBeLessThan(.2);expect(old.state).toBe("INSUFFICIENT_DATA");});
 it("assigns configurable exploration without permanently locking a category",()=>{expect(allocateExploreExploit(10,.7)).toEqual({exploit:7,explore:3,exploitRatio:.7,explorationRatio:.30000000000000004});const rows=recommendCategories([{categoryKey:"beauty",accountEffect:.6,categoryMomentum:80,confidence:.9},{categoryKey:"home",accountEffect:0,categoryMomentum:55,confidence:.6},{categoryKey:"new",accountEffect:0,categoryMomentum:70,confidence:.1}],.25);expect(rows.find(x=>x.categoryKey==="beauty")?.action).toBe("EXPAND");expect(rows.find(x=>x.categoryKey==="new")?.action).toBe("TEST");});
 it("treats follower milestones as recheck triggers, never Affiliate proof",()=>{const i=milestoneTransition({previousFollowers:900,currentFollowers:1000,milestones:[100,500,1000,5000],commerce:commerceFixtures.I})[0],j=milestoneTransition({previousFollowers:4900,currentFollowers:5200,milestones:[100,500,1000,5000],commerce:commerceFixtures.J})[0],k=milestoneTransition({previousFollowers:4900,currentFollowers:5200,milestones:[5000],commerce:commerceFixtures.K})[0];expect(i.commerceRecheckStatus).toBe("PENDING");expect(i.transitionEligible).toBe(false);expect(j.transitionEligible).toBe(true);expect(k.commerceRecheckStatus).toBe("REAUTH_REQUIRED");});
 it("resolves commerce states only from authoritative readiness",()=>{const score=calculateGrowthOptimizationScore(growthFixtures.B);expect(resolveGrowthState({snapshotCount:8,score,rollingGrowthRate:8,priorRollingRate:7,commerce:commerceFixtures.I,recheckRequired:true})).toBe("COMMERCE_RECHECK");expect(resolveGrowthState({snapshotCount:8,score,rollingGrowthRate:8,priorRollingRate:7,commerce:commerceFixtures.J,recheckRequired:true})).toBe("COMMERCE_READY");expect(resolveGrowthState({snapshotCount:8,score,rollingGrowthRate:8,priorRollingRate:7,commerce:commerceFixtures.K,recheckRequired:true})).toBe("COMMERCE_BLOCKED");});
 it("creates controlled, duplicate-safe, originality-compatible experiments",()=>{const a=planGrowthExperiment({ownerId:"o",accountId:"a",topic:"skin",axis:"HOOK",control:"question",variant:"demo"}),b=planGrowthExperiment({ownerId:"o",accountId:"a",topic:"skin",axis:"HOOK",control:"question",variant:"demo"});expect(a).toEqual(b);expect(a?.originalityRequired).toBe(true);expect(Object.keys(a!.variant).filter(k=>a!.variant[k]!==a!.control[k])).toEqual(["HOOK"]);});
 it("creates stable retry keys while delayed evidence gets a new key",()=>{expect(growthEvidenceHash({day:1,followers:10})).toBe(growthEvidenceHash({day:1,followers:10}));expect(growthEvidenceHash({day:1,followers:10})).not.toBe(growthEvidenceHash({day:2,followers:15}));});
 it("feeds safe Growth context to Creative Brain",()=>{const patterns=learnAccountPatterns("A",accountPatternFixtures),categories=recommendCategories([{categoryKey:"beauty",accountEffect:.6,categoryMomentum:80,confidence:.9}],.25),recommendation=buildGrowthRecommendation({state:"GROWING",patterns,categories,confidence:.8});expect(recommendation.nextAction).toBe("SCALE_HOOK");expect(recommendation.commerceClaimsAllowed).toBe(false);expect(recommendation.cta).not.toMatch(/ซื้อ|ตะกร้า|shop/i);});
 it("allows Growth publishing without Shop while preserving all publish gates",()=>{expect(growthPublishingAllowed({compliance:true,originality:true,accountHealth:true,withinCap:true,consent:true,shopAuthorized:false})).toBe(true);expect(growthPublishingAllowed({compliance:true,originality:false,accountHealth:true,withinCap:true,consent:true,shopAuthorized:false})).toBe(false);});
 it("simulates 10 account-specific 30-day histories",()=>{const states=new Set<string>();for(let a=0;a<10;a+=1){const history=Array.from({length:30},(_,day)=>calculateGrowthOptimizationScore({...growthFixtures.B,followerDelta:a%3===0?0:day%5+1,accountRelativeImprovement:(a-5)/10,sampleSize:day+1}));const final=history.at(-1)!;states.add(resolveGrowthState({snapshotCount:30,score:final,rollingGrowthRate:a%3===0?0:a+1,priorRollingRate:a%3===0?1:a,commerce:a===9?commerceFixtures.I:commerceFixtures.L,recheckRequired:a===9}));}expect(states.has("PLATEAU")).toBe(true);expect(states.has("GROWING")||states.has("ACCELERATING")).toBe(true);expect(states.has("COMMERCE_RECHECK")).toBe(true);});
});
