import type {SupabaseClient} from "@supabase/supabase-js";import type {GrowthState,NextGrowthAction} from "./types";
export interface GrowthProfileRow{id:string;tiktok_account_id:string;growth_state:GrowthState;growth_score:number|null;preferred_categories_json:Array<{categoryKey:string;action:string;score:number}>;winning_hooks_json:Array<{value:string;state:string;score:number}>;winning_angles_json:Array<{value:string;state:string;score:number}>;winning_ctas_json:Array<{value:string;state:string;score:number}>;posting_preferences_json:Record<string,unknown>;exploit_ratio:number;exploration_ratio:number;confidence:number;updated_at:string;}
export interface GrowthSnapshotRow{id:string;tiktok_account_id:string;snapshot_at:string;follower_count:number|null;follower_delta:number|null;views:number|null;engagement:number|null;follower_attribution_confidence:number;category_performance_json:Record<string,number>;availability_json:Record<string,string>;}
export interface GrowthExperimentRow{id:string;tiktok_account_id:string;hypothesis:string;control_json:Record<string,string>;variant_json:Record<string,string>;changed_axis:string;status:string;originality_required:boolean;start_at:string|null;end_at:string|null;created_at:string;}
export interface GrowthMilestoneRow{id:string;tiktok_account_id:string;follower_count:number;milestone_value:number;milestone_type:string;reached_at:string;commerce_recheck_required:boolean;commerce_recheck_status:string;}
export interface GrowthRecommendationRow{id:string;tiktok_account_id:string;next_action:NextGrowthAction;category_key:string|null;hook:string|null;angle:string|null;opening:string;cta:string;experiment_axis:string|null;confidence:number;originality_required:boolean;commerce_claims_allowed:boolean;created_at:string;}
async function rows<T>(client:SupabaseClient,table:string,owner:string,limit=500){const {data,error}=await client.from(table).select("*").eq("owner_id",owner).order("created_at",{ascending:false}).limit(limit);if(error)throw new Error(`Growth query failed: ${error.message}`);return(data??[]) as T[];}
export async function getGrowthOverview(client:SupabaseClient,owner:string){const [accountsResult,profiles,snapshots,experiments,milestones,recommendations]=await Promise.all([client.from("tiktok_accounts").select("id,display_name,username,follower_count,effective_mode").eq("owner_id",owner).order("created_at"),rows<GrowthProfileRow>(client,"growth_strategy_profiles",owner),rows<GrowthSnapshotRow>(client,"growth_account_snapshots",owner),rows<GrowthExperimentRow>(client,"growth_experiments",owner),rows<GrowthMilestoneRow>(client,"growth_milestones",owner),rows<GrowthRecommendationRow>(client,"growth_recommendations",owner)]);if(accountsResult.error)throw new Error(accountsResult.error.message);const accounts=(accountsResult.data??[]) as Array<{id:string;display_name:string;username:string|null;follower_count:number;effective_mode:string}>;return{accounts:accounts.map(account=>({account,profile:profiles.find(x=>x.tiktok_account_id===account.id)??null,latestSnapshot:snapshots.find(x=>x.tiktok_account_id===account.id)??null,experiments:experiments.filter(x=>x.tiktok_account_id===account.id),milestones:milestones.filter(x=>x.tiktok_account_id===account.id),recommendation:recommendations.find(x=>x.tiktok_account_id===account.id)??null})),profiles,snapshots,experiments,milestones,recommendations};}
export async function getGrowthAccount(client:SupabaseClient,owner:string,id:string){const overview=await getGrowthOverview(client,owner);const item=overview.accounts.find(x=>x.account.id===id);if(!item)return null;return{...item,snapshots:overview.snapshots.filter(x=>x.tiktok_account_id===id).toSorted((a,b)=>b.snapshot_at.localeCompare(a.snapshot_at)),milestones:item.milestones.toSorted((a,b)=>b.reached_at.localeCompare(a.reached_at))};}
export function summarizeGrowth(overview:Awaited<ReturnType<typeof getGrowthOverview>>){const growth=overview.accounts.filter(x=>x.account.effective_mode==="GROWTH"),fastest=growth.toSorted((a,b)=>(b.latestSnapshot?.follower_delta??-Infinity)-(a.latestSnapshot?.follower_delta??-Infinity)).slice(0,3);return{growthAccounts:growth.length,plateau:growth.filter(x=>x.profile?.growth_state==="PLATEAU").length,milestones:overview.milestones.length,rechecks:overview.milestones.filter(x=>x.commerce_recheck_required&&x.commerce_recheck_status==="PENDING").length,fastest,winningHooks:overview.profiles.flatMap(x=>x.winning_hooks_json??[]).filter(x=>x.state==="WINNING").slice(0,5),winningCategories:overview.profiles.flatMap(x=>x.preferred_categories_json??[]).filter(x=>x.action==="EXPAND").slice(0,5)};}
